### PR TITLE
[sdk-chroot] Utilize profile.d for bash setup. JB#56751

### PR DESCRIPTION
**Pull request by vigejolla**

### CODE REVIEW

**Comment by vigejolla** [comment]
Please note, that this changes the order in which the files are read: Now .mersdk.profile is read as a profile file, i.e. before .bashrc. Thus setting PS1 in .mersdk.profile doesn't quite work, as .bashrc will quite likely overwrite PS1. Setting PS1 in .bash_profile, with the help of $SAILFISH_SDK, works.

**Comment by martyone** [comment]
Looks promising. Doesn't it read the profile twice when opening an interactive shell?

**Comment by martyone** [comment]
It might be. Some messages may get issued twice, etc., so we should really aim for single pass. Maybe just passing `-l` either to the outer shell or the inner one based on the arguments?

**Comment by vigejolla** [comment]
> It might be. Some messages may get issued twice, etc., so we should really aim for single pass. Maybe just passing `-l` either to the outer shell or the inner one based on the arguments?

Definitely worth a try.

**Comment by vigejolla** [comment]
Rewrote, separating the working principle depending on the arguments: When starting an interactive shell, all "magic" is done under profile.d. When executing a single command, we use the old method, with one difference though: We don't utilize a login shell. This mimics the behaviour with ssh, with one minor difference: We don't read .bashrc.

**Comment by martyone** [comment]
Rebased

**Comment by martyone** [comment]
Debugged, polished.

**Review by martyone — APPROVED** [review]

**Pull request merged**
