### PR TITLE
Do not produce short-circuited RPMs

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by martyone** [comment]
Requires https://git.merproject.org/mer-core/rpm/merge_requests/9

**Comment by mkosola** [comment]
What is short-circuited RPM?

**Comment by martyone** [comment]
@mkosola produced with rpmbuild --short-circuit, tainted with an unsatisfiable dependency on rpmlib(ShortCircuited) - check e.g. https://bugzilla.redhat.com/show_bug.cgi?id=671210

**Comment by mkosola** [comment]
@martyone Ah, thank you!

**Comment by saukko** [comment]
We should add dependency to the rpm version that contains this new option so that one can't by accident use newer mb2 with old rpm.

In general LGTM :+1:

**Comment by martyone** [comment]
@saukko that's a bit tricky as our rpm patching is not reflected in package version, only the OBS-generated release number changes. Checking other packages' specs, none seems to be referring that.

**Pull request merged**
