### PR TITLE
Jb54305

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Review by vigejolla — APPROVED** [review]
LGTM. But it leaves me wondering why did the old behaviour result in the error?

**Comment by martyone** [comment]
With the original approach the host-side code could temporarily see either empty or incomplete content.

**Comment by vigejolla** [comment]
> With the original approach the host-side code could temporarily see either empty or incomplete content.

Yes, I understand that, but it just seem unlikely that the host-side code would want to read the content at that precise moment. Is it watching for changes in the file?

**Comment by martyone** [comment]
Yup, it watches it.

**Pull request merged**
