### PR TITLE
[sdk-setup] Remove jolla-ca zypper requires. JB#54898

### PR DESCRIPTION
**Pull request by etaishev**

### CODE REVIEW

**Comment by martyone** [comment]
Simply dropping it doesn't look right to me. Shouldn't we replace it with some more generic capability?

**Comment by etaishev** [comment]
I can't see all Jolla code, but as i understand from PRs in jb49356 - jolla-ca will be in sdk any way

**Comment by vigejolla** [comment]
> I can't see all Jolla code, but as i understand from PRs in jb49356 - jolla-ca will be in sdk any way

The point of the the check files is that a warning will be displayed if the user tries to remove the package. So instead of just removing jolla-ca, we should have jolla-ca provide some more generic capability, let's say 'vendor-ca'. And then have the check require that instead.

**Comment by etaishev** [comment]
Update PR. Add check for vendor-ca. 
Who can update 'jolla-ca' for `Provides: vendor-ca`?

**Review by okodron — APPROVED** [review]

**Comment by etaishev** [comment]
Update on current master

**Review by vigejolla — APPROVED** [review]
typo in the commit message (virual -> virtual). Otherwise lgtm.

**Comment by etaishev** [comment]
@martyone Can you please see

**Comment by stanislavmaksimov** [comment]
@martyone, @vigejolla, could you please have a look

**Pull request merged**
